controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_directory:
  resource: "routes/application"
  name_prefix: api_
  prefix: /api/
  type: directory
